### ISSUE TITLE
[Issue Report] I Can't run the test

### ISSUE THREAD

**Issue by Miuler** [http-server-rs/http-server#478]
**Description**

When I run the test, I get the following error:

```rust
error: #[derive(RustEmbed)] folder '/home/miuler/proyectos/http-server/crates/http-server/../file-explorer-ui/public/dist' does not exist. cwd: '/home/miuler/proyectos/http-server'
  --> crates/http-server/src/handler/file_explorer/mod.rs:25:1
   |
25 | / #[folder = "../file-explorer-ui/public/dist"]
26 | | struct FileExplorerAssets;
   | |__________________________^

error[E0599]: no function or associated item named `get` found for struct `FileExplorerAssets` in the current scope
  --> crates/http-server/src/handler/file_explorer/mod.rs:52:49
   |
26 | struct FileExplorerAssets;
   | ------------------------- function or associated item `get` not found for this struct
...
52 |         if let Some(file) = FileExplorerAssets::get(path) {
   |                                                 ^^^ function or associated item not found in `FileExplorerAssets`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following traits define an item `get`, perhaps you need to implement one of them:
           candidate #1: `Embed`
           candidate #2: `SliceIndex`

error[E0599]: no function or associated item named `get` found for struct `FileExplorerAssets` in the current scope
  --> crates/http-server/src/handler/file_explorer/mod.rs:65:41
   |
26 | struct FileExplorerAssets;
   | ------------------------- function or associated item `get` not found for this struct
...
65 |         let index = FileExplorerAssets::get("index.html").unwrap();
   |                                         ^^^ function or associated item not found in `FileExplorerAssets`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following traits define an item `get`, perhaps you need to implement one of them:
           candidate #1: `Embed`
           candidate #2: `SliceIndex`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `http-server` (bin "http-server" test) due to 3 previous errors
Process finished with exit code 101
```

**Comment by LeoBorai** [comment]
Hey @Miuler! Apologies for the inconvenience, yes currently this project is under migration and the `main` branch holds new version changes. For stable version you can take a look at: https://github.com/http-server-rs/http-server/releases/tag/v0.8.9

**Comment by LeoBorai** [comment]
Hey @Miuler tests have been introduced in #480. Feel free to take a look at them.
You can see them running in: https://github.com/http-server-rs/http-server/actions/runs/14459059120/job/40548150277#step:6:497

So far theres only two:

https://github.com/http-server-rs/http-server/blob/675ff3b0b26dc5f19c8a1473ea6d1aaafd9ec23b/test/src/smoke.rs#L7-L39

Feel free to open a PR adding more!
